name: Pull request checks
on: pull_request

jobs:
  lint:
    name: "Static code analysis"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter pub get
      - name: Lint analysis
        run: flutter analyze
